name: "Releases"

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Set node version
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install
      run: |
        export DETECT_CHROMEDRIVER_VERSION=true
        npm ci
        npm run setheapsize

    - name: Lint
      run: npx grunt lint

    - name: Unit Tests
      run: |
        npm test
        npm run testnodeconsumer

    - name: Production Build
      run: npx grunt prod

    - name: UI Tests
      run: |
        sudo apt-get install xvfb
        xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: build/prod/*.zip
